### ISSUE TITLE
Allow to test multiple root level charts from CI

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#100]
Add charts to the matrix similar like we do the scenarios.

```diff
     strategy:
       fail-fast: false
       matrix:
         # Choose tags corresponding to the version of Kind being used.
         # At a minimum, we should test the currently supported versions of
         # Kubernetes, but can go back farther as long as we don't need heroics
         # to pull it off (i.e. kubectl version juggling).
         k8s:
           - v1.26.0
           - v1.25.3
           - v1.24.7
           - v1.23.13
           - v1.22.15
           - v1.21.14
+        charts:
+          - ${{ fromJson(needs.build-matrix.outputs.charts) }}
         values:
           - ${{ fromJson(needs.build-matrix.outputs.tests) }}
```

This will allow us to test more root level charts later on.

Suggested is to introduce one folder level so we can group the test scenarios per chart.

```shell
tree .github/tests      
.github/tests
└── spire
    ├── extras
    │   └── values.yaml
    ├── no-spire-controller-manager
    │   └── values.yaml
    ├── prometheus
    …
```

**Comment by marcofranssen** [comment]
See [8943d7e](https://github.com/spiffe/helm-charts/commit/8943d7e30efe309fc01dcfdb106e8bdf6b584258) for an attempt to achieve this.

This needs some second thoughts though as we are facing the following:

`ct install` will install all the charts that are in the charts folder.

Our workflow currently makes a matrix for all the chart-scenarios meaning with our current workflow it will also attempt to use our values/scenarios for the spire chart on any other chart.

An approach to work around this is to use following option.

```shell
$ ct install --help
…
--excluded-charts strings              Charts that should be skipped. May be specified multiple times
                                             or separate values with commas
…
```

However doing so will also spin up unneccesary runners for all the tests that should be skipped.

**Comment by kfox1111** [comment]
Not sure its a good idea or not, but if its watching a chart directory, maybe we need multiple chart directories?
