### ISSUE TITLE
Check if we need to migrate any APIs for k8s 1.27 release

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#135]
https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/

**Comment by kfox1111** [comment]
I don't see anything in the list that should block us.

Is there a 1.27 beta or something we could add as a non blocking test?

**Comment by kfox1111** [comment]
Closing since we are already testing in the gate.
