### ISSUE TITLE
Image mirroring

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts#139]
Before 1.0, we need to ensure all images can be overridden to point to local mirrors.

**Comment by faisal-memon** [comment]
Would a global registry flag help here?

**Comment by kfox1111** [comment]
+1 to a global registry flag. was planning on making a pr for that at some point.

**Comment by marcofranssen** [comment]
I think we support this since merging the test images PR. @kfox1111 can you confirm and close the issue?

**Comment by kfox1111** [comment]
Yeah. https://github.com/spiffe/helm-charts/pull/186 was the last of it.

But we should be careful not to reintroduce it when we break out the charts.

Closing.
