### ISSUE TITLE
dataStorage vs persistence value

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts#171]
The very common convention is to have a persistence flag for dealing with volumes. This chart is using dataStorage instead. We should probably consider changing this flag before 1.0.

**Comment by marcofranssen** [comment]
We are naming the things as they are named on the Spire side. So dataStorage is named because of the dataStorage config option in the spire config.

**Comment by kfox1111** [comment]
Its a helm chart though and the convention that most helm users expect is persistence rather then dataStore. Which way will be less confusing to users?

**Comment by kfox1111** [comment]
We talked it over during the last meeting and decided to go with persistence.
