### ISSUE TITLE
Support AWS PCA upstream

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/helm-charts#21]
[AWS PCA](https://docs.aws.amazon.com/privateca/latest/userguide/PcaWelcome.html) is a widely used for an upstream CA. The official SPIRE helm chart should support the [AWS PCA plugin](https://github.com/spiffe/spire/blob/main/doc/plugin_server_upstreamauthority_aws_pca.md).

**Comment by marcofranssen** [comment]
Accidentally created a duplicate. The duplicate does contain a bit more context for new contributors, so closing this one. See #78
