### ISSUE TITLE
Replicas > 1 is allowed with sqlite driver and it shouldn't be.

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts#268]
We need to check for replicas > 1 when the sqlite driver is being used and block install/upgrades. It is not a supported or even workable configuration.

**Comment by edwbuck** [comment]
Desired behavior here is to issue an error statement that "The SQLite3 Datastore cannot support more than one Server instance, please select another datastore or set the number of server instances to one"

That way the error message embeds the fix.
