### ISSUE TITLE
Tornjak review issues.

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts#284]
There were a few issues identified by a final review of the branch that still need addressing. Referencing here so we don't forget:
https://github.com/spiffe/helm-charts/pull/234#pullrequestreview-1429118074

For convenience here the unhandled feedback.

- [x] tornjak frontend missing in README.md (https://github.com/spiffe/helm-charts/pull/234/files#r1196910210)
- [x] Question on Tornjak metadata backend (hardcoded at "insert metadata") https://github.com/spiffe/helm-charts/pull/234/files#r1195518417
- [x] #291
- [x] Add "(Not for production)" to the end of the tornjak enabled variables. #297

**Comment by marcofranssen** [comment]
@mrsabath Could you check the open questions see above in this issue description. (middle checkbox).

**Comment by kfox1111** [comment]
The hardcoded bit is needed to get standalone without auth working. It will be enhanced to make it configurable when user auth support is added.

**Comment by kfox1111** [comment]
one more thing from the review...
tornjak-frontend.enabled / spire-server.tornjak.enabled, should we put 'Experimental: ' at the begging of the readme docstring for it?
we have the warning for after its enabled. but maybe one in the docs that way for before?

**Comment by marcofranssen** [comment]
Yes probably add something like `(Not for production)` at the enabled values.

**Comment by kfox1111** [comment]
All done. Thanks! :)
