### ISSUE TITLE
"spire-lib.kubectl-image" not defined

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#335]
```shell
$ helm template -n spire-system --values examples/production/values.yaml spire ./charts/spire
Error: template: spire/charts/spiffe-oidc-discovery-provider/templates/pre-delete-hook.yaml:64:27: executing "spire/charts/spiffe-oidc-discovery-provider/templates/pre-delete-hook.yaml" at <{{template "spire-lib.kubectl-image" (dict "appVersion" $.Chart.AppVersion "image" .Values.deleteHook.image "global" .Values.global "KubeVersion" .Capabilities.KubeVersion.Version)}}>: template "spire-lib.kubectl-image" not defined
```

This failure happens 50% of the time. So if you don't get it first time, just run, this helm template command couple of times and you will see it happens like 50% of the time.

**Comment by kfox1111** [comment]
Its working consistently for me checking out main and running:
helm template -n spire-system --values examples/production/values.yaml spire ./charts/spire

Same with the gate tests. they seem to be reliable.

Could there be a bad git checkout, version of helm or maybe some bad memory involved? I haven't seen helm ever have a state where it is 50% reliable with a macro like this.

**Comment by kfox1111** [comment]
actually, I'm not seeing a file named charts/spire/charts/spiffe-oidc-discovery-provider/templates/pre-delete-hook.yaml

An experiment that got left in your tree? Sounds like of like something related to https://github.com/spiffe/helm-charts/issues/330?

**Comment by kfox1111** [comment]
`$.Chart.AppVersion "image" .Values.deleteHook.image "global" .Values.global "KubeVersion" .Capabilities.KubeVersion.Version)}`  that looks strange. why is it $.Chart.Appversion but .Capabilities.KubeVersion.Version?

**Comment by kfox1111** [comment]
looks like its done the same way here though: ./charts/spire/charts/spire-server/templates/pre-upgrade-hook.yaml
and doing some testing, thats working consistently for me too.

So, maybe back to other files in your checkout, helm version, or memory issue?

**Comment by faisal-memon** [comment]
Im not able to reproduce this one either.

**Comment by faisal-memon** [comment]
I was able to reproduce this today. I think it happens when i try to install after a failure but not 100% sure.

**Comment by kfox1111** [comment]
Have any logs? was it spire-lib or spire-server?

**Comment by marcofranssen** [comment]
Found the issue. Due to running the helm charttesting tool from a different branch I ended up with `.tgz` files for all subcharts in `charts/spire/charts`. Therefore those got precedence over the sourcecode, causing those issues for me. Now I probably also know how to fix my issues on the other branch, will take care in Makefile to clean those tgz files to prevent the issues for others.
