### ISSUE TITLE
Support tolerations for spire-agent

### ISSUE THREAD

**Issue by timbuchwaldt** [spiffe/helm-charts#380]
The agent only schedules on untainted nodes. This is insufficient for clusters with specialized nodes for certain workloads (or even in-cluster controlplanes)

**Comment by kfox1111** [comment]
Your right. That's definitely an oversight. Thanks for reporting this issue.

**Comment by kfox1111** [comment]
Looks like spiffe-csi-driver lacks the option as well. I'll add that too.
