### ISSUE TITLE
Poorly named property in upstream-spire-agent / spire-agent

### ISSUE THREAD

**Issue by edwbuck** [spiffe/helm-charts#428]
The 

```
namespaceOverride: spire-system
```

property indicates that the namespace is being overridden, which is odd, because the entire declarative nature of K8s objects is such that one should specify the namespace.  By adding the word override, it indicates an approach / policy and a namespace when the only relevant information is the namespace.

Please rename 'namespaceOverride' to 'namespace' and let the context of where that namespace resides control which Kubernetes objects the namespace impacts.

**Comment by marcofranssen** [comment]
In Helm you don't need a `namespace` in the valueFile. The namespace is based on the `--namespace` flag. This override is to support other usecases where some object need to go into a different namespace then the rest of the `Helm` chart.

**Comment by kfox1111** [comment]
At least for the bitnami series of charts, namespaceOverride value is commonly used for this.
https://github.com/search?q=repo%3Abitnami%2Fcharts%20namespaceOverride&type=code

**Comment by kfox1111** [comment]
Looks like they are having a conversation about it in ingress-nginx as well:
https://github.com/kubernetes/ingress-nginx/issues/8663#issuecomment-1710115972
