### ISSUE TITLE
ACTION REQUIRED: Changes to pulling Chainguard Images

### ISSUE THREAD

**Issue by chainguard-alerter** [spiffe/helm-charts#442]
Hey there [Chainguard](https://github.com/chainguard-dev) here.

We noticed that you are using [Chainguard Images](https://github.com/chainguard-images/images), thank you! We wanted to make you aware of an upcoming change that will impact your project.

Starting August 16, 2023 public users will no longer be able to pull images from our registry (cgr.dev/chainguard) by tags other than `latest` or `latest-dev`. Please see [the announcement](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) for more information.

You are currently using the following.

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/charts/tornjak-frontend/values.yaml:

- cgr.dev/chainguard/bash:5.2.15

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/charts/spire-server/values.yaml:

- cgr.dev/chainguard/bash:5.2.15

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/charts/spire-agent/values.yaml:

- cgr.dev/chainguard/wait-for-it:latest-20230517
- cgr.dev/chainguard/bash:5.2.15

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/charts/spire-agent/README.md:

- cgr.dev/chainguard/wait-for-it:latest-20230517
- cgr.dev/chainguard/bash:5.2.15

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/charts/spiffe-oidc-discovery-provider/values.yaml:

- cgr.dev/chainguard/bash:5.2.15

In https://github.com/spiffe/helm-charts/blob/a167ce68901a2b08d44367aa3a6da7612a64afc6/charts/spire/README.md:

- cgr.dev/chainguard/wait-for-it:latest-20230517
- cgr.dev/chainguard/bash:5.2.15

Our goal is to prevent your project from experiencing any disruptions. Please see [the migration guide](https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users) for options.

If there's more we can do to help please reply to this issue or email us at [support@chainguard.dev](mailto:support@chainguard.dev).

Thank you!

**Comment by kfox1111** [comment]
So, we need to switch to :latest@sha256xxxxx on all these...

**Comment by kfox1111** [comment]
Renewing the call for https://github.com/spiffe/helm-charts/pull/249

**Comment by faisal-memon** [comment]
Thanks chainguard. I think the digestabot mentioned in the migration guide would work well here.

**Comment by faisal-memon** [comment]
Discussed with @kfox1111 . digest-a-bot won't work for our use case as it assumes image and tag are together. For us they are separate configurables.

**Comment by amouat** [comment]
Hey, I work with Chainguard - I'm not sure what you mean by "separate configurables"? I'd love to come up with something that works for you if I can. Do you mean you need access to older tags?

**Comment by amouat** [comment]
Ah cool, that is useful!

I'll open an issue on digestabot.
