### ISSUE TITLE
No use of example.org

### ISSUE THREAD

**Issue by edwbuck** [spiffe/helm-charts#447]
In the values.yaml files and anywhere else that contains anything that looks like a domain name (like trust domains) example.org should not be used.  It provides the "feel" of correct configuration when it is known to be a non-working domain (pre DNS RFCs).

Instead, no default value should be provided, and an error message should be issued that indicates one needs to set the specific values.yaml key.

**Comment by faisal-memon** [comment]
Decision not to move forward with this.
