### ISSUE TITLE
spire-oidc does not start if federatesWith contains a down federated endpoint

### ISSUE THREAD

**Issue by drewwells** [spiffe/helm-charts#454]
Spire oidc logs

### Example spiffeid
```
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-system-federates
spec:
  federatesWith:
  - non-existent.example.com
  spiffeIDTemplate: spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{
    .PodSpec.ServiceAccountName }}
```

### Repo Steps:
- Configure clusterspiffeids.spire.spiffe.io with a federatesWith to a down spire federation endpoint
- Attempt to start oidc
- See the above logs and oidc container terminates

### Results
```
Defaulted container "spiffe-oidc-discovery-provider" out of: spiffe-oidc-discovery-provider, nginx
time="2023-08-17T19:03:49Z" level=info msg="Serving HTTP" address=/run/spire/oidc-sockets/spire-oidc-server.sock network=unix
time="2023-08-17T19:03:49Z" level=debug msg="Polling started" interval=10s
time="2023-08-17T19:03:51Z" level=warning msg="Failed to fetch JWKS from the Workload API" error="rpc error: code = PermissionDenied desc = no identity issued"
time="2023-08-17T19:04:01Z" level=warning msg="Failed to fetch JWKS from the Workload API" error="rpc error: code = PermissionDenied desc = no identity issued"
```

### Expected
oidc gives some error that federated endpoint is down, or starts despite missing one federatesWith endpoint.

**Comment by kfox1111** [comment]
Thinking this is a spire issue, not an issue with the helm chart. Probably should move this issue to the spiffe/spire repo?

**Comment by kfox1111** [comment]
After reading some documentation, this really feels like spire is working as intended:
https://spiffe.io/docs/latest/architecture/federation/readme/#get-the-bootstrap-trust-bundle
Mentions:
```
spire-server entry create \
	-parentID <SPIRE Agent's SPIFFE ID> \
	-spiffeID spiffe://broker.example/webapp \
	-selector unix:user:webapp \
	-federatesWith "spiffe://stockmarket.example"
```
> By specifying the -federatesWith flag, once this registration entry is created, when the webapp’s SPIRE Server asks for an SVID it will get one from the broker’s SPIRE Server with the spiffe://broker.example/webapp identity, along with the trust bundle associated to the stockmarket.example trust domain.

That the trust bundle is not available as its pointing to a nonexisting one, is expected behavior I think and workload issuance is blocked waiting for it to come online.

This can be avoided by having multiple ClusterSPIFFEID's that target different workloads I think.

**Comment by drewwells** [comment]
It might be, but it needs to report errors about the actual issue. This error doesn't mention anything about federation endpoint being down. It's also only a warning when it prevents any JWTs from being minted
`level=warning msg="Failed to fetch JWKS from the Workload API" error="rpc error: code = PermissionDenied desc = no identity issued"`

**Comment by kfox1111** [comment]
Its broken in the same way K8s workloads usually break. Its in its currently requested state to the best of its ability. When the broken endpoint comes up, so will the workload. Not sure how we make that any better in the chart?

**Comment by drewwells** [comment]
Well the federation is wired up in CRs, so we should set the status of the CRs (controller manager issue) if a federated endpoint is down. As for the error messages, that could be improved in spire itself. I opened an issue over there as well

**Comment by kfox1111** [comment]
Yeah. Both controller manager and/or spire could have some changes to help. But not sure if there is anything that can be done in the helm chart that would help? Can you think of anything? Else, we might just want to close this ticket.

**Comment by drewwells** [comment]
Closed for spire and scm open issues
