### ISSUE TITLE
Can't install sub charts independently

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/helm-charts#63]
We should be able to install the components individually. When i try i see these errors:

SPIRE Agent:
```bash
$ helm template .
Error: template: spire-agent/templates/daemonset.yaml:1:19: executing "spire-agent/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: spire-agent/templates/configmap.yaml:55:12: executing "spire-agent/templates/configmap.yaml" at <dig "telemetry" "prometheus" "enabled" .Values.telemetry.prometheus.enabled .Values.global>: error calling dig: interface conversion: interface {} is nil, not map[string]interface {}

Use --debug flag to render out invalid YAML
```

SPIRE Server: 
```bash
$ helm template .
Error: template: spire-server/templates/statefulset.yaml:1:19: executing "spire-server/templates/statefulset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: spire-server/templates/configmap.yaml:85:12: executing "spire-server/templates/configmap.yaml" at <dig "telemetry" "prometheus" "enabled" .Values.telemetry.prometheus.enabled .Values.global>: error calling dig: interface conversion: interface {} is nil, not map[string]interface {}

Use --debug flag to render out invalid YAML
```

CSI Driver:
```bash
$ helm template .
Error: template: spiffe-csi-driver/templates/daemonset.yaml:102:21: executing "spiffe-csi-driver/templates/daemonset.yaml" at <include "spire.agent-socket-path" .>: error calling include: template: no template "spire.agent-socket-path" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

OIDC:
```bash
$ helm template .
Error: template: spiffe-oidc-discovery-provider/templates/configmap.yaml:33:45: executing "spiffe-oidc-discovery-provider/templates/configmap.yaml" at <include "spire.agent-socket-path" .>: error calling include: template: no template "spire.agent-socket-path" associated with template "gotpl"

Use --debug flag to render out invalid YAML
```

**Comment by marcofranssen** [comment]
If we really want to install components separately we have 2 options in my view.

1. Move out all the subcharts as root level charts (individually versioned), this will bring additional maintenance burden as well more advanced test setup to test the combination of charts. (preferably I postpone this as much as possible until people have burning usecases for that)

2. Use root level `enabled` values in the root chart. So you can simply install the root chart using `enabled: false` for the components you don't want. This allows to control things like following as well.
   - Auto enable other subcharts that have interdependencies.
     - Auto enable spiffe-csi-driver if spire-agent is enabled, spire-agent after all needs the csi-driver in current setup (or take the csi-driver as argument from values file, in case you installed that separately already). 
     - Auto enable spire-agent if spiffe-oidc-provider is enabled as it depends on the agent socket.

**Comment by kfox1111** [comment]
Managing turning off all the things gets more and more painful as things are added. I really like the way kube-prometheus-stack works where its highly opinionated and you can just install it and get a really well integrated into k8s setup. or if you want, you can use the prometheus-community helm charts to install all the pieces individually.

**Comment by marcofranssen** [comment]
> Managing turning off all the things gets more and more painful as things are added. I really like the way kube-prometheus-stack works where its highly opinionated and you can just install it and get a really well integrated into k8s setup. or if you want, you can use the prometheus-community helm charts to install all the pieces individually.

Agree, that is also why this chart is using subcharts to have a opiniated implementation of a basic Spire setup.

I think we should document the usecases more clearly on what and why should be separately installable to decide on a manageable strategy to refactor the required things.

**Comment by kfox1111** [comment]
We agreed to delay the effort to split out the subcharts, but not to not do it. We should probably discuss it at the next meeting.

**Comment by kfox1111** [comment]
Or maybe two different things are getting mixed up here? The description talks about the inability to install the charts from the subcharts directory. but the issue has also been used as a way to track the need of root level charts. Maybe we should update the ticket to be explicit about the root level chart thing?

**Comment by marcofranssen** [comment]
Kevin I'm not saying we will never have more top level charts. That is a separate thing from what is reported in this issue. Just saying you can't use subcharts the way described in this issue, so this issue could be closed as we can't make the subcharts work like this. We could create a new issues to move certain components to a top level chart, to be picked at a later stage.
