### ISSUE TITLE
Upgrading an existing installation of spire helm chart fails on spire-controller-manager

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#72]
This could be an installation order thing where spire-controller-manager is replaced while the CRD is being deployed at the same time. Subsequent run to perform the upgrade makes the install succeed.

```shell
$ helm  upgrade -n spire-system --install --values ../../../philips-labs/helm-charts/.local/spire-values.yaml spire ./charts/spire
Error: UPGRADE FAILED: cannot patch "spire-controller-manager-service-account-based" with kind ClusterSPIFFEID: Internal error occurred: failed calling webhook "vclusterspiffeid.kb.io": failed to call webhook: Post "https://spire-controller-manager-webhook.spire-system.svc:443/validate-spire-spiffe-io-v1alpha1-clusterspiffeid?timeout=10s": no endpoints available for service "spire-controller-manager-webhook"
$ helm  upgrade -n spire-system --install --values ../../../philips-labs/helm-charts/.local/spire-values.yaml spire ./charts/spire
Release "spire" has been upgraded. Happy Helming!
NAME: spire
LAST DEPLOYED: Wed Mar  1 11:32:51 2023
NAMESPACE: spire-system
STATUS: deployed
REVISION: 3
NOTES:
Installed spire…
```

How to reproduce.

```shell
$ helm -n spire-system uninstall spire
$ git checkout release
$ helm upgrade -n spire-system --install --values ../../../philips-labs/helm-charts/.local/spire-values.yaml spire ./charts/spire
Release "spire" has been installed. Happy Helming!
NAME: spire
LAST DEPLOYED: Wed Mar  1 11:32:51 2023
NAMESPACE: spire-system
STATUS: deployed
REVISION: 1
NOTES:
Installed spire…
$ git checkout main
$ helm upgrade -n spire-system --install --values ../../../philips-labs/helm-charts/.local/spire-values.yaml spire ./charts/spire
Error: UPGRADE FAILED: cannot patch "spire-controller-manager-service-account-based" with kind ClusterSPIFFEID: Internal error occurred: failed calling webhook "vclusterspiffeid.kb.io": failed to call webhook: Post "https://spire-controller-manager-webhook.spire-system.svc:443/validate-spire-spiffe-io-v1alpha1-clusterspiffeid?timeout=10s": no endpoints available for service "spire-controller-manager-webhook"
$ helm upgrade -n spire-system --install --values ../../../philips-labs/helm-charts/.local/spire-values.yaml spire ./charts/spire
Release "spire" has been upgraded. Happy Helming!
NAME: spire
LAST DEPLOYED: Wed Mar  1 11:35:51 2023
NAMESPACE: spire-system
STATUS: deployed
REVISION: 2
NOTES:
Installed spire…
```

Maybe we can control some things with the rollout strategy on the spire-server statefulset.

**Comment by kfox1111** [comment]
The best solution would be to have multiple parallel copies of the webhook. Until that is broken out though, the next best option would be to make controller-manager-webhook.yaml failurePolicy configurable and change it to more permissive. The objects managed should be privileged anyway, so not too bad to lighten validation to make upgrades smoother in the mean time.

**Comment by faisal-memon** [comment]
Spent some time researching this but unfortunately not able to come up with a great solution. One possible solution is to use a pre-upgrade hook to change the `failurePolicy` on the webhook to ignore and then change it back with a post-upgrade hook. 

Seems like the same problem could happen on regular install If the statefulset is delayed in coming up.

**Comment by marcofranssen** [comment]
That Pre-Upgrade hook might be a great workaround. Did you already try this? Wouldn't it automatically restore the failurePolicy due to the definition in the Helm Chart?

**Comment by faisal-memon** [comment]
> That Pre-Upgrade hook might be a great workaround. Did you already try this? Wouldn't it automatically restore the failurePolicy due to the definition in the Helm Chart?

Will test today, I was trying to find other ways to work around this issue. Disabling the webhook means someone could put an invalid clusterspiffeid through, so im a little worried about that.

**Comment by kfox1111** [comment]
I've avoided those hooks as it slows down upgrades a fair amount, causes churn, and doesn't fit too well in with gitops.

**Comment by kfox1111** [comment]
a clusterspiffeid can only be set by a clusteradmin? if so, then they are only breaking themselves.

**Comment by kfox1111** [comment]
changing failurePolicy: away from Fail would let this work better.
