### ISSUE TITLE
Unable to attach or mount volumes spire-oidc-discovery-provider

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts#80]
In some situations the spire-oidc-discovery-provider fails to boot on a fresh install.

```shell
Unable to attach or mount volumes: unmounted volumes=[spiffe-workload-api], unattached volumes=[kube-api-access-xmq62 spiffe-workload-api spire-oidc-sockets spire-oidc-config]: timed out waiting for the condition
```

Killing the pod does the trick to retry and fix it as a workaround, but would be great if we can fix this in a way it just always succeeds on a fresh install.

Are more people able to reproduce this?

**Comment by marcofranssen** [comment]
Found if I put `priorityClassName: system-node-critical` on the agent daemonsets, I'm unable to reproduce the issue, so far.

Should we put this by default on the spiffe-csi-driver?
Should we put this by default on the spire-agent, or shall we use `system-cluster-critical` for this component?
Should we just document this and leave it to the enduser?

My feeling is we need to make the spiffe-csi-driver at least `system-node-critical`.

**Comment by kfox1111** [comment]
shouldn't need to do that by default. How full are those nodes?

If nothing else, it would be nice if we produced some prod recommendations?

I know its not standard to setup stuff like resource requests/limits by default. but we could provide in the documentation a reference values file with all that stuff turned on and set to some sane defaults a user could download and tweak?

**Comment by faisal-memon** [comment]
It would be good to get a root cause. I dont think its good to update settings without knowing why they fix the problem

**Comment by faisal-memon** [comment]
Document for now, address with https://github.com/spiffe/helm-charts/pull/99/files#diff-e5d95a142cf1134e77e5c83dfeac07f49d1f433253a8b07d11a652c784403a6bR1
